-- PaTiGroup settings and marker logic. Run via PaTiAdmin/tools/check.sh.
local wow = require("wow_api")

local function load()
    return wow.loadAddonFile("Logic.lua", {}).Logic
end

describe("Logic.Migrate", function()
    it("creates defaults for players of PaTiGroup <= 0.4 (no saved variables before)", function()
        local db = load().Migrate(nil)
        assert.same({ 8, 7, 5, 6, 4, 3, 2, 1 }, db.markers)
        assert.is_false(db.locked)
        assert.is_true(db.showPull)
        assert.equal("", db.note)
        assert.equal(1, db.schema)
    end)

    it("keeps saved values and replaces a broken marker list", function()
        local db = load().Migrate({ showPull = false, note = "Kara Montag", markers = { 8 }, x = 3 })
        assert.is_false(db.showPull)
        assert.equal("Kara Montag", db.note)
        assert.equal(8, #db.markers)
        assert.equal(3, db.x)
    end)
end)

describe("Logic.SetSlot", function()
    it("moves a marker instead of showing it twice", function()
        local Logic = load()
        local markers = Logic.SetSlot({ 8, 7, 5, 6, 4, 3, 2, 1 }, 1, 1)
        assert.same({ 1, 7, 5, 6, 4, 3, 2, 8 }, markers)
    end)

    it("can empty a slot", function()
        local Logic = load()
        local markers = Logic.SetSlot({ 8, 7, 5, 6, 4, 3, 2, 1 }, 2, 0)
        assert.same({ 8, 5, 6, 4, 3, 2, 1 }, Logic.VisibleMarkers(markers))
    end)
end)

describe("Logic.RestoreDefaults", function()
    it("keeps the note and the position", function()
        local db = load().RestoreDefaults({ note = "hi", x = 1, showPull = false, markers = { 1, 0, 0, 0, 0, 0, 0, 0 } })
        assert.equal("hi", db.note)
        assert.equal(1, db.x)
        assert.is_true(db.showPull)
        assert.same({ 8, 7, 5, 6, 4, 3, 2, 1 }, db.markers)
    end)
end)

describe("Logic helpers", function()
    it("builds the reset macro text: every marker to yourself, then clear", function()
        local text = load().ResetMacroText()
        assert.matches("^/tm %[@player%] 1\n", text)
        assert.matches("/tm %[@player%] 8\n/tm %[@player%] 0$", text)
    end)

    it("cleans the note: one line, at most 200 characters", function()
        local Logic = load()
        assert.equal("a b", Logic.CleanNote("a\nb"))
        assert.equal(200, #Logic.CleanNote(string.rep("x", 300)))
        assert.equal("", Logic.CleanNote(nil))
    end)

    it("counts roles", function()
        local counts = load().CountRoles({ "TANK", "HEALER", "DAMAGER", "DAMAGER", "NONE" })
        assert.same({ TANK = 1, HEALER = 1, DAMAGER = 2, NONE = 1 }, counts)
    end)
end)
